language: node_js
node_js:
- '5'
- '4'
services:
- rabbitmq
deploy:
  provider: npm
  email: clysuva@gmail.com
  api_key:
    secure: kpl1Fu7fl5dnsuPzE1UhYDgMZ+NLjAu8stlnJVFlAHQHiibF45RrQdQvIuhKHNkl5/3mzsrhb4kqLQNx+SEmIavMnme8r/XP42YEeQqlT1KHm30DXHzXYc/ojY1p2L6BfG1pNxWmni7RY6y/J7luoS8I02Zv4BnwGI7Q3koPdFtS+11M/kBh3QmpI+922O7jKPu4J2Ek0xgWUOwVw0TmGkjRjVoCIksxmtj1Ob0CQDQYCZUkKR5Nv3iO9EIfVJcLtnMde90YxAt+XFt3OcTYAozdUTji3TEdTx0C1GMvhzjAjiH/P0b9Lyf/xTkov5xIbtXrRtH8j7XiVez/njEIq8TLQNj5RSe94vDsQHzAu0Dj5BDxUc1gzGw+dp++9dQT5xuOsgpgmRZ27hl8Vb+QNYySJl1q4fS3sVnevdtpgYG7OE3CVnIJ6nYBM8bAZ+KYrHA0Flg4xmIFxAiKJqUEdUW9kb1xg8Oao8vqkucqFiXo+Xn97TcvpdAtQ4QarvghMHuIoENMMOA/LaDYFe36runG4owxRx8dBzFt6afqSRHNVuXqzIKDGhivE4knm+7+qK39DxHL0Mjlrg8oKf9HxaUXHx8EWzmqGPPG/9Sb8+K7ZW8Le+MV0OH6k/lQrIp5xYaJbi8rhJ2L6RtXZczOHdDY8Su6zISrdb2veLAC7No=
  on:
    tags: true
    branch: master
    repo: esticade/esticade.js